fos_user:
  db_driver: orm
  user_class: App\Entity\Security\User
  firewall_name: main
  service:
      user_manager: app.user_manager
  from_email:
    address: "%env(MAILER_SENDER_ADDRESS)%"
    sender_name: "%env(MAILER_SENDER_NAME)%"
