fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\Security\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"
  service:
    user_manager: app.user_manager
